In [7]:
 import numpy as np

# ----------------------------
# 1. Input sentence
# ----------------------------
sentence = "I love machine learning"

# ----------------------------
# 2. Tokenization
# ----------------------------
tokens = sentence.lower().split()
print("Tokens:", tokens)

# ----------------------------
# 3. Vocabulary creation
# ----------------------------
vocab = {word: idx for idx, word in enumerate(tokens)}
vocab_size = len(vocab)
print("Vocabulary:", vocab)

# ----------------------------
# 4. Token Embedding Matrix
# ----------------------------
embedding_dim = 6  # size of embedding vector
np.random.seed(42)

embedding_matrix = np.random.rand(vocab_size, embedding_dim)

# ----------------------------
# 5. Lookup Embedding for each token
# ----------------------------
token_embeddings = np.array([
    embedding_matrix[vocab[token]] for token in tokens
])

print("\nToken Embeddings:")
print(token_embeddings)

# ----------------------------
# 6. Positional Embedding
# ----------------------------
max_len = len(tokens)
positional_embedding = np.random.rand(max_len, embedding_dim)

print("\nPositional Embeddings:")
print(positional_embedding)

# ----------------------------
# 7. Final Embedding (Token + Position)
# ----------------------------
final_embeddings = token_embeddings + positional_embedding

print("\nFinal Embeddings (Token + Positional):")
print(final_embeddings)


Tokens: ['i', 'love', 'machine', 'learning']
Vocabulary: {'i': 0, 'love': 1, 'machine': 2, 'learning': 3}

Token Embeddings:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]]

Positional Embeddings:
[[0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691]
 [0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802]]

Final Embeddings (Token + Positional):
[[0.8306101  1.73589027 0.93166772 1.11289292 0.74843321 0.20244493]
 [0.66562846 1.03670027 0.6661666  1.65695812 0.98621653 1.7783072 ]
 [1.13705641 0.31001122 0.86605799 0.623557   0.42628048 1.01993334]
 [0.46633354 1.20054954 0.87063288 0.80201615 0.60