In [1]:
import numpy as np

# -----------------------------
# 1. Input Sentence
# -----------------------------
sentence = "deep learning models use token embedding"

# -----------------------------
# 2. Tokenization (simple split)
# -----------------------------
tokens = sentence.lower().split()
print("Tokens:", tokens)

# -----------------------------
# 3. Build Vocabulary
# -----------------------------
vocab = {word: idx for idx, word in enumerate(set(tokens))}
print("Vocab:", vocab)

# Convert tokens -> token IDs
token_ids = np.array([vocab[t] for t in tokens])
print("Token IDs:", token_ids)

# -----------------------------
# 4. Lookup Token Embedding
# -----------------------------
vocab_size = len(vocab)
embedding_dim = 6   # embedding vector size

# Random embedding matrix
np.random.seed(42)
embedding_matrix = np.random.rand(vocab_size, embedding_dim)

# Lookup embeddings
token_embeddings = embedding_matrix[token_ids]
print("\nToken Embeddings:\n", token_embeddings)

# -----------------------------
# 5. Positional Embedding (Sinusoidal)
# -----------------------------
def positional_encoding(seq_len, d_model):
    PE = np.zeros((seq_len, d_model))
    for pos in range(seq_len):
        for i in range(0, d_model, 2):
            PE[pos, i] = np.sin(pos / (10000 ** (i / d_model)))
            if i+1 < d_model:
                PE[pos, i+1] = np.cos(pos / (10000 ** (i / d_model)))
    return PE

pos_embeddings = positional_encoding(len(tokens), embedding_dim)

print("\nPositional Embeddings:\n", pos_embeddings)

# -----------------------------
# 6. Final Input Embedding
# token embedding + positional embedding
# -----------------------------
final_embeddings = token_embeddings + pos_embeddings

print("\nFinal Input Embeddings:\n", final_embeddings)


Tokens: ['deep', 'learning', 'models', 'use', 'token', 'embedding']
Vocab: {'embedding': 0, 'models': 1, 'learning': 2, 'token': 3, 'deep': 4, 'use': 5}
Token IDs: [4 2 1 5 3 0]

Token Embeddings:
 [[0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643]
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]
 [0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]]

Positional Embeddings:
 [[ 0.          1.          0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.04639922  0.99892298  0.00215443  0.99999768]
 [ 0.90929743 -0.41614684  0.0926985   0.99569422  0.00430886  0.99999072]
 [ 0.14112001 -0.9899925   0.1387981   0.9903207   0.00646326  0.99997911]
 [-0.7568025  -0.65364362  0.18459872  0.98281398  0.00861763 